import React, { useState } from 'react';
import { ShieldCheck, HelpCircle } from 'lucide-react';

interface ConfidenceScoreProps {
  score: number; // e.g. 82
  sourcesCount?: number;
}

export const ConfidenceScore: React.FC<ConfidenceScoreProps> = ({
  score = 82,
  sourcesCount = 4,
}) => {
  const [showTooltip, setShowTooltip] = useState(false);

  const getScoreColor = (val: number) => {
    if (val >= 80) return 'bg-emerald-500';
    if (val >= 60) return 'bg-amber-500';
    return 'bg-blue-600';
  };

  return (
    <div className="mt-4 rounded-xl border border-slate-200/90 dark:border-slate-800 bg-slate-50/70 dark:bg-slate-800/50 p-3 sm:p-3.5">
      <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
        {/* Label & Tooltip */}
        <div className="flex items-center gap-2">
          <div className="flex h-5 w-5 items-center justify-center rounded-md bg-emerald-100 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-400">
            <ShieldCheck className="h-3.5 w-3.5" />
          </div>
          <span className="text-xs font-bold text-slate-800 dark:text-slate-200">
            Answer Confidence
          </span>

          {/* Info Tooltip */}
          <div className="relative inline-block">
            <button
              type="button"
              onMouseEnter={() => setShowTooltip(true)}
              onMouseLeave={() => setShowTooltip(false)}
              onClick={() => setShowTooltip(!showTooltip)}
              className="text-slate-400 hover:text-slate-600 dark:hover:text-slate-300 focus:outline-hidden"
              aria-label="Confidence score explanation"
            >
              <HelpCircle className="h-3.5 w-3.5" />
            </button>

            {showTooltip && (
              <div className="absolute left-1/2 bottom-full mb-1.5 -translate-x-1/2 z-30 w-64 rounded-lg bg-slate-900 dark:bg-slate-800 px-3 py-2 text-[11px] font-normal text-white shadow-lg pointer-events-none text-center border border-slate-700">
                Confidence score will be generated by the verification module.
                <div className="absolute top-full left-1/2 -translate-x-1/2 border-4 border-transparent border-t-slate-900 dark:border-t-slate-800" />
              </div>
            )}
          </div>
        </div>

        {/* Sources citation note */}
        <span className="text-[11px] font-medium text-slate-500 dark:text-slate-400">
          Grounded in <span className="font-semibold text-slate-700 dark:text-slate-300">{sourcesCount} retrieved sources</span>
        </span>
      </div>

      {/* Progress Bar & Percentage */}
      <div className="mt-2.5 flex items-center gap-3">
        <div className="relative h-2 flex-1 overflow-hidden rounded-full bg-slate-200 dark:bg-slate-700">
          <div
            className={`h-full rounded-full transition-all duration-500 ${getScoreColor(score)}`}
            style={{ width: `${score}%` }}
          />
        </div>
        <span className="font-mono text-xs font-bold text-slate-800 dark:text-slate-200 shrink-0">
          {score}%
        </span>
      </div>
    </div>
  );
};
